In [2]:
import pandas as pd
import numpy as np
print("OK")

OK

In [20]:
customers= pd.read_csv(r"E:\برتفوليو كامل\Portfolio Data Analysis\python\Global Electronics & Smart Home Retail\Data File Before\customers.csv")
products= pd.read_csv(r"E:\برتفوليو كامل\Portfolio Data Analysis\python\Global Electronics & Smart Home Retail\Data File Before\products.csv")
orders= pd.read_csv(r"E:\برتفوليو كامل\Portfolio Data Analysis\python\Global Electronics & Smart Home Retail\Data File Before\orders.csv")
order_items=pd.read_csv(r"E:\برتفوليو كامل\Portfolio Data Analysis\python\Global Electronics & Smart Home Retail\Data File Before\order_items.csv")
print("OK")

OK

In [4]:
customers.head(5)

,CustomerID,FullName,Email,Phone,Country,City,SignupDate
0,CUST_15796,Aisha Johnson,NaN,invalid_phone,USA,Jeddah,2022-01-01 00:00:00
1,CUST_00861,Linda Ibrahim,user_1@gmail.com,+1-779-592-9240,USA,London,2022-01-01 00:01:00
2,CUST_38159,Linda Williams,user_2@gmail.com,+1-652-132-3566,Germany,New York,2022-01-01 00:02:00
3,CUST_44733,Jennifer Miller,user_3@gmail.com,+1-626-790-3795,USA,Jeddah,2022-01-01 00:03:00
4,CUST_11285,Ahmed Brown,user_4@gmail.com,+1-417-190-2280,USA,Toronto,2022-01-01 00:04:00

In [6]:
customers.tail(5)

,CustomerID,FullName,Email,Phone,Country,City,SignupDate
50495,CUST_25877,Robert Jones,user_314@gmail.com,+1-486-435-5569,Germany,Jeddah,2022-01-01 05:14:00
50496,CUST_09476,Elizabeth Williams,user_11449@gmail.com,+1-329-700-5726,Canada,London,2022-01-08 22:49:00
50497,CUST_05737,Michael Smith,user_30745@gmail.com,+1-710-521-2700,Germany,Berlin,2022-01-22 08:25:00
50498,CUST_23554,John Williams,user_29702@gmail.com,+1-372-373-9452,USA,Jeddah,2022-01-21 15:02:00
50499,CUST_42332,James Smith,user_27658@gmail.com,+1-664-824-3426,UK,Jeddah,2022-01-20 04:58:00

In [7]:
products.head(5)

   ProductID     ProductName     Category  StandardCost  UnitPrice
0  PROD_0001  Smart Device 1        Audio        815.33     895.49
1  PROD_0002  Smart Device 2  Smartphones        803.53    1576.05
2  PROD_0003  Smart Device 3        Audio        213.89    1089.44
3  PROD_0004  Smart Device 4  Accessories        141.12     548.28
4  PROD_0005  Smart Device 5        Audio        622.26    1750.47

In [8]:
products.tail(5)

      ProductID        ProductName     Category  StandardCost  UnitPrice
2495  PROD_2496  Smart Device 2496        Audio       1168.38    1260.23
2496  PROD_2497  Smart Device 2497        Audio        264.59    1572.22
2497  PROD_2498  Smart Device 2498  Smartphones        885.80     860.22
2498  PROD_2499  Smart Device 2499  Accessories        742.54     262.15
2499  PROD_2500  Smart Device 2500  Accessories       1131.25    1767.13

In [9]:
orders.head(5)

,OrderID,CustomerID,OrderDate,ShippingDate,OrderStatus,SalesChannel
0,ORD_000001,CUST_02718,2023-01-01 00:00:00.000000000,2023-01-04 00:00:00.000000000,Shipped,Store
1,ORD_000002,CUST_19100,2023-01-01 00:10:31.300208668,2023-01-06 00:10:31.300208668,Completed,Web
2,ORD_000003,CUST_16783,2023-01-01 00:21:02.600417336,2023-01-06 00:21:02.600417336,Completed,online
3,ORD_000004,CUST_12526,2023-01-01 00:31:33.900626004,2023-01-04 00:31:33.900626004,Shipped,Store
4,ORD_000005,CUST_07187,2023-01-01 00:42:05.200834672,2023-01-02 00:42:05.200834672,Completed,online

In [10]:
orders.tail(5)

,OrderID,CustomerID,OrderDate,ShippingDate,OrderStatus,SalesChannel
149995,ORD_149996,CUST_05559,2025-12-31 23:17:54.799165328,2026-01-03 23:17:54.799165328,Completed,online
149996,ORD_149997,CUST_16622,2025-12-31 23:28:26.099373984,2026-01-01 23:28:26.099373984,Completed,Store
149997,ORD_149998,CUST_04717,2025-12-31 23:38:57.399582656,2026-01-02 23:38:57.399582656,Completed,Online
149998,ORD_149999,CUST_09863,2025-12-31 23:49:28.699791328,2026-01-05 23:49:28.699791328,Shipped,online
149999,ORD_150000,CUST_29460,2026-01-01 00:00:00.000000000,2026-01-04 00:00:00.000000000,Pending,Online

In [21]:
order_items.head(5)

    OrderItemID     OrderID  ProductID  Quantity  Discount
0  ITEM_0000001  ORD_051491  PROD_1804         1      0.00
1  ITEM_0000002  ORD_069954  PROD_1051         2      0.05
2  ITEM_0000003  ORD_004716  PROD_0618         2      0.10
3  ITEM_0000004  ORD_021937  PROD_1094         1     -0.05
4  ITEM_0000005  ORD_004810  PROD_1608         1      0.00

In [22]:
order_items.tail(5)

         OrderItemID     OrderID  ProductID  Quantity  Discount
349995  ITEM_0349996  ORD_058675  PROD_2232        -1       0.0
349996  ITEM_0349997  ORD_131457  PROD_0064         2       0.0
349997  ITEM_0349998  ORD_066058  PROD_0338         2       0.0
349998  ITEM_0349999  ORD_097589  PROD_0062         2       0.0
349999  ITEM_0350000  ORD_017019  PROD_1710         1       0.1

In [23]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50500 entries, 0 to 50499
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  50500 non-null  object
 1   FullName    50500 non-null  object
 2   Email       47132 non-null  object
 3   Phone       50500 non-null  object
 4   Country     50500 non-null  object
 5   City        50500 non-null  object
 6   SignupDate  50500 non-null  object
dtypes: object(7)
memory usage: 2.7+ MB

In [24]:
c_customers=customers.copy()

Cleaning Table Customers

In [42]:
c_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50500 entries, 0 to 50499
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  50500 non-null  object
 1   FullName    50500 non-null  object
 2   Email       50500 non-null  object
 3   Phone       50500 non-null  object
 4   Country     50500 non-null  object
 5   City        50500 non-null  object
 6   SignupDate  50500 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(6)
memory usage: 2.7+ MB

In [45]:
c_customers.head(5)

,CustomerID,FullName,Email,Phone,Country,City,SignupDate
0,CUST_15796,Aisha Johnson,Not Available,invalid_phone,USA,Jeddah,2022-01-01 00:00:00
1,CUST_00861,Linda Ibrahim,user_1@gmail.com,+1-779-592-9240,USA,London,2022-01-01 00:01:00
2,CUST_38159,Linda Williams,user_2@gmail.com,+1-652-132-3566,Germany,New York,2022-01-01 00:02:00
3,CUST_44733,Jennifer Miller,user_3@gmail.com,+1-626-790-3795,USA,Jeddah,2022-01-01 00:03:00
4,CUST_11285,Ahmed Brown,user_4@gmail.com,+1-417-190-2280,USA,Toronto,2022-01-01 00:04:00

In [39]:
c_customers["Email"].isna().sum()

np.int64(0)

In [37]:
(c_customers["Email"].str.strip()=='').sum()

np.int64(0)

In [38]:
c_customers["Email"]= c_customers["Email"].fillna("Not Available")

In [40]:
c_customers["SignupDate"]=pd.to_datetime(
    c_customers["SignupDate"],
    errors="coerce")

In [41]:
c_customers["SignupDate"].isna().sum()

np.int64(0)

In [44]:
c_customers.replace(r'^\s*$', np.nan, regex=True).isnull().sum()

CustomerID    0
FullName      0
Email         0
Phone         0
Country       0
City          0
SignupDate    0
dtype: int64

In [47]:
c_customers["City"].unique()

array(['Jeddah', 'London', 'New York', 'Toronto', 'Dubai', 'Berlin'],
      dtype=object)

In [48]:
c_customers["Country"].unique()

array(['USA', 'Germany', 'Canada', 'UK', 'UAE'], dtype=object)

In [49]:
c_customers["CustomerID"].nunique()

31644

In [57]:
c_customers.duplicated().sum()

np.int64(0)

In [63]:
print("Duplicate rows:", c_customers.duplicated().sum())
print("Null values:\n", c_customers.isnull().sum())

Duplicate rows: 0
Null values:
 CustomerID    1
FullName      0
Email         0
Phone         0
Country       0
City          0
SignupDate    0
dtype: int64

In [64]:
c_customers["CustomerID"].isna().sum()

np.int64(1)

In [66]:
c_customers = c_customers.dropna(subset=['CustomerID'])

In [56]:
c_customers=(
    c_customers.drop_duplicates()
)

In [59]:
c_customers["CustomerID"].duplicated().sum()

np.int64(0)

In [58]:
c_customers = c_customers.drop_duplicates(subset=['CustomerID'], keep='first')

Cleaning Table Products

In [68]:
products.head(5)

   ProductID     ProductName     Category  StandardCost  UnitPrice
0  PROD_0001  Smart Device 1        Audio        815.33     895.49
1  PROD_0002  Smart Device 2  Smartphones        803.53    1576.05
2  PROD_0003  Smart Device 3        Audio        213.89    1089.44
3  PROD_0004  Smart Device 4  Accessories        141.12     548.28
4  PROD_0005  Smart Device 5        Audio        622.26    1750.47

In [81]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     2500 non-null   object
 1   ProductName   2500 non-null   object
 2   Category      2500 non-null   object
 3   StandardCost  2500 non-null   float64
 4   UnitPrice     2471 non-null   float64
dtypes: float64(2), object(3)
memory usage: 97.8+ KB

In [70]:
c_products=products.copy()

In [80]:
c_products["UnitPrice"].isna().sum()

np.int64(0)

In [73]:
invalid_prices = products[products['UnitPrice'] <= 0]
len(invalid_prices)

10

In [76]:
c_products.loc[c_products['UnitPrice'] <= 0, 'UnitPrice'] = np.nan

In [77]:
c_products["UnitPrice"]=(
    c_products["UnitPrice"].fillna(
        c_products.groupby("Category")["UnitPrice"].transform("mean")
    ))

In [82]:
c_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     2500 non-null   object
 1   ProductName   2500 non-null   object
 2   Category      2500 non-null   object
 3   StandardCost  2500 non-null   float64
 4   UnitPrice     2500 non-null   float64
dtypes: float64(2), object(3)
memory usage: 97.8+ KB

In [91]:
mask=(c_products["StandardCost"] > c_products["UnitPrice"]).fillna(False)
len(mask)

2500

يمكننا جعل سعر البيع يساوي تكلفة التصنيع مضافاً إليها هامش ربح بسيط (مثلاً 20% كحد أدنى):

In [92]:
c_products.loc[mask, 'UnitPrice'] = c_products.loc[mask, 'StandardCost'] * 1.20

In [93]:
c_products["Category"].unique()

array(['Audio', 'Smartphones', 'Accessories', 'Home Appliances',
       'Laptops'], dtype=object)

In [94]:
# إزالة المسافات الزائدة من الأطراف لجميع الأعمدة النصية في جدول المنتجات
text_columns = c_products.select_dtypes(include=['object']).columns
for col in text_columns:
    c_products[col] = c_products[col].astype(str).str.strip()

print("تم تنظيف وإزالة المسافات الزائدة بنجاح!")

تم تنظيف وإزالة المسافات الزائدة بنجاح!

Cleaning Table Orders

In [95]:
c_orders=orders.copy()

In [97]:
c_orders.head(5)

,OrderID,CustomerID,OrderDate,ShippingDate,OrderStatus,SalesChannel
0,ORD_000001,CUST_02718,2023-01-01 00:00:00.000000000,2023-01-04 00:00:00.000000000,Shipped,Store
1,ORD_000002,CUST_19100,2023-01-01 00:10:31.300208668,2023-01-06 00:10:31.300208668,Completed,Web
2,ORD_000003,CUST_16783,2023-01-01 00:21:02.600417336,2023-01-06 00:21:02.600417336,Completed,online
3,ORD_000004,CUST_12526,2023-01-01 00:31:33.900626004,2023-01-04 00:31:33.900626004,Shipped,Store
4,ORD_000005,CUST_07187,2023-01-01 00:42:05.200834672,2023-01-02 00:42:05.200834672,Completed,online

In [100]:
c_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       150000 non-null  object
 1   CustomerID    150000 non-null  object
 2   OrderDate     150000 non-null  datetime64[ns]
 3   ShippingDate  150000 non-null  datetime64[ns]
 4   OrderStatus   150000 non-null  object
 5   SalesChannel  150000 non-null  object
dtypes: datetime64[ns](2), object(4)
memory usage: 6.9+ MB

In [99]:
c_orders["OrderDate"]=pd.to_datetime(
    c_orders["OrderDate"],
    errors="coerce")

c_orders["ShippingDate"]=pd.to_datetime(
    c_orders["ShippingDate"],
    errors="coerce"
)

In [101]:
invalid_dates=(c_orders[c_orders["ShippingDate"] < c_orders["OrderDate"]])
len(invalid_dates)

200

In [102]:
c_orders= c_orders[~(c_orders["ShippingDate"] < c_orders["OrderDate"])]

In [113]:
c_orders["SalesChannel"]=c_orders["SalesChannel"].str.strip()
c_orders["SalesChannel"].unique()

C:\Users\RAI-ZEN\AppData\Local\Temp\ipykernel_17168\566006451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_orders["SalesChannel"]=c_orders["SalesChannel"].str.strip()

array(['Store', 'Online'], dtype=object)

In [112]:
channel_map={
    'online':'Online',
    'Web':'Online',
    'store':'Store'
}
c_orders["SalesChannel"]=c_orders["SalesChannel"].replace(channel_map)

C:\Users\RAI-ZEN\AppData\Local\Temp\ipykernel_17168\1322301596.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_orders["SalesChannel"]=c_orders["SalesChannel"].replace(channel_map)

In [114]:
c_orders.isnull().sum()

OrderID         0
CustomerID      0
OrderDate       0
ShippingDate    0
OrderStatus     0
SalesChannel    0
dtype: int64

In [115]:
# حذف الصفوف التي تحتوي على قيم مفقودة في الأرقام الأساسية
c_orders.dropna(subset=['OrderID', 'CustomerID'], inplace=True)

C:\Users\RAI-ZEN\AppData\Local\Temp\ipykernel_17168\587475292.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_orders.dropna(subset=['OrderID', 'CustomerID'], inplace=True)

In [116]:
c_orders["OrderStatus"].unique()

array(['Shipped', 'Completed', 'Cancelled', 'Pending'], dtype=object)

Cleaning Table Order Items

In [117]:
order_items.head(5)

    OrderItemID     OrderID  ProductID  Quantity  Discount
0  ITEM_0000001  ORD_051491  PROD_1804         1      0.00
1  ITEM_0000002  ORD_069954  PROD_1051         2      0.05
2  ITEM_0000003  ORD_004716  PROD_0618         2      0.10
3  ITEM_0000004  ORD_021937  PROD_1094         1     -0.05
4  ITEM_0000005  ORD_004810  PROD_1608         1      0.00

In [118]:
c_order_items= order_items.copy()

In [119]:
c_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350000 entries, 0 to 349999
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   OrderItemID  350000 non-null  object
 1   OrderID      350000 non-null  object
 2   ProductID    350000 non-null  object
 3   Quantity     350000 non-null  int64
 4   Discount     350000 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 13.4+ MB

In [120]:
invalid_qtys= c_order_items[c_order_items["Quantity"]<=0]
len(invalid_qtys)

35080

In [121]:
c_order_items= c_order_items[c_order_items["Quantity"]>0]

In [122]:
invalid_dis= c_order_items[c_order_items["Discount"]<0]
len(invalid_dis)

15735

In [123]:
c_order_items.loc[c_order_items["Discount"]<0,"Discount"]=0.0

In [125]:
c_order_items.isna().sum()

OrderItemID    0
OrderID        0
ProductID      0
Quantity       0
Discount       0
dtype: int64

In [126]:
# حفظ الجداول النظيفة في ملفات CSV جديدة للداشبورد
c_customers.to_csv('cleaned_customers.csv', index=False)
c_products.to_csv('cleaned_products.csv', index=False)
c_orders.to_csv('cleaned_orders.csv', index=False)
c_order_items.to_csv('cleaned_order_items.csv', index=False)

تم تصدير وحفظ جميع الجداول النظيفة بنجاح وجاهزة للـ Power BI!